### ISSUE TITLE
KWStyle crashes with exit code -6

### ISSUE THREAD

**Issue by catskul** [Kitware/KWStyle#37]
version: 1.0.1+git3224cf2-1

KWStyle -xml /home/catskul/work/knight/knight/KWStyle.xml -gcc /home/catskul/work/knight/knight/src/robot/libraries/libSafetyBoardSim/libSafetyBoardSim/SafetyBoardSim.cpp -o /tmp/tmpQ40iP8

`terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 18446744073709548929) > this->size() (which is 4488)
Aborted (core dumped)`

stack trace:

```
#0  0x00007ffff74ab418 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffff74ad01a in __GI_abort () at abort.c:89
#2  0x00007ffff7ae484d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7ae26b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7ae2701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7ae2919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7b0b3f7 in std::__throw_out_of_range_fmt(char const*, ...) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00005555555cdb06 in kws::Parser::FindFunction(unsigned long, char const*) const ()
#8  0x0000555555622c14 in kws::Parser::CheckFunctions(char const*, unsigned long) ()
#9  0x00005555555c94e4 in kws::Parser::Check(char const*, char const*) ()
#10 0x00005555555af45f in main ()
````

KWStyle.xml
```
<?xml version="1.0" encoding="iso-8859-1"?>
<!--
<Project>This is my project</Project>
<ProjectLogo>Project Logo</ProjectLogo>
<KWStyleLogo>KWSTYleLogo</KWStyleLogo>
<Description>
<LineLength>81</LineLength>
-->
<InternalVariables>
  <regex>m_[A-Z]|g_[A-Z]|EIGEN_MAKE_ALIGNED_OPERATOR_NEW</regex>
  <alignment>false</alignment>
  <private>1</private>
</InternalVariables>

<SemicolonSpace>0</SemicolonSpace>

<DeclarationOrder>
  <public>0</public>
  <protected>1</protected>
  <private>2</private>
</DeclarationOrder>

<!--
<EndOfFileNewLine>1</EndOfFileNewLine>
-->

<Tabs>1</Tabs>

<Spaces>1</Spaces>

<!--
<Indent>
 <type>SPACE</type>
 <size>2</size>
 <noHeader>true</noHeader>
 <allowBlockLine>true</allowBlockLine>
</Indent>
-->


<!--
<Header>
    <location>KWStyle.header</location>
  <checkSpacesEndOfLine>true</checkSpacesEndOfLine>
  <cvsFormat>true</cvsFormat>
</Header>
<IfNDefDefine>.*[NameOfClass].*</IfNDefDefine>
-->

<Typedefs>
  <regex>[A-Z]</regex>
  <allignment>false</allignment>
</Typedefs>

<Namespace>crl</Namespace>

<NameOfClass>
  <name>[NameOfClass]</name>
  <prefix></prefix>
</NameOfClass>

<Comments>
  <begin>/**</begin>
  <middle> *</middle>
  <end>*/</end>
  <emptyLineBeforeClass>false</emptyLineBeforeClass>
  <checkWrongComment>true</checkWrongComment>
  <checkMissingComments>true</checkMissingComments>
</Comments>

<EmptyLines>2</EmptyLines>

<Template>[a-z]</Template>


<!--
<BlackList>myBlackList.txt</BlackList>

<Struct>[a-z]</Struct>

<StatementPerLine>
    <maxNumber>1</maxNumber>
    <checkInline>0</checkInline>
</StatementPerLine>
-->

<VariablePerLine>
    <maxNumber>1</maxNumber>
</VariablePerLine>

<BadCharacters>false</BadCharacters>

<MemberFunctions>
    <regex>bool|operator|[A-Z]|static_cast|=|std</regex>
</MemberFunctions>

<Functions>
    <regex>bool|operator|catch|[A-Z]|\]|static_cast|=|"|runtime_error</regex>
</Functions>


</Description>
```

SafetyBoardSim.cpp
```
#include "SafetyBoardSim.h"

//#include <knightsafety/knightsafety.h>
#include <knightsafety/eventloop.h>
#include <knightsafety/globaldata.h> // FIXME this eventually should not be necessary
#include <knightsafety/knightsafety_shim.h>
#include <knightsafety/knightsafety_sensoreval.h>
//#include <knightsafety_sensoreval.h>
//#include <dropoffsensors.h>

#include <boost/format.hpp>

#include <bitset>
#include <iostream>
#include <string>
#include <memory>

#include <libConsolePrint/ConsolePrint.h>
// The ConsolePrint's Macro Interface needs to be told what code to use
#define PRINT_MESSAGE( level, code ) crl::common::ConsolePrint( level, "SafetyBoardSim" ) code
#include <libConsolePrint/MacroInterface.h>
#include <knightsafety_sensoreval.h>


using std::cout;
using std::bitset;
using std::endl;
using std::shared_ptr;
using std::make_shared;
using fmt = boost::format;


namespace crl
{
namespace knight
{

SafetyBoardSim::SafetyBoardSim()
    : m_Dropoff(    std::make_shared<Dropoff_t>()    )
    , m_Orientation(std::make_shared<Orientation_t>())
    , m_Proximity(  std::make_shared<Proximity_t>()  )
{
    init_safety_subsystems(m_Orientation.get(), m_Dropoff.get(), m_Proximity.get());
}


//auto SafetyBoardSim::OldStyleSafetyStuff(
//    std::shared_ptr<DropOffSensorReaderMsg> const &dropOffMsg,
//    std::shared_ptr<WheelEncoderReaderMsg> const &encoderMsg
//) -> std::shared_ptr<knightsafety_lowleveloutputdata_t>
//{
//    knightsafety_lowlevelinputdata_t lowLevelInputData = {0, 0, 0, 0, 0, 0, 0, 0};
//
//    lowLevelInputData.dropoff_frontleft_voltticks  = dropOffMsg->DropOffFrontLeft;
//    lowLevelInputData.dropoff_frontright_voltticks = dropOffMsg->DropOffFrontRight;
//    lowLevelInputData.dropoff_sideleft_voltticks   = dropOffMsg->DropOffSideLeft;
//    lowLevelInputData.dropoff_sideright_voltticks  = dropOffMsg->DropOffSideRight;
//
//    lowLevelInputData.wheelencoder_left_ticks  = encoderMsg->LeftTicks;
//    lowLevelInputData.wheelencoder_right_ticks = encoderMsg->RightTicks;
//
//    auto lowLevelOutputData = make_shared<knightsafety_lowleveloutputdata_t>(knightsafety_lowleveloutputdata_t{KNIGHTSAFETY_SAFE});
//    set_knightsafety_safetyflags(&lowLevelInputData, lowLevelOutputData.get());
//
//    std::map<std::string, bool> flags;
//    flags["DROPOFF_FRONTLEFT_UNSAFE"]  = lowLevelOutputData->safety_flags & KNIGHTSAFETY_DROPOFFFRONTLEFT_UNSAFE;
//    flags["DROPOFF_FRONTRIGHT_UNSAFE"] = lowLevelOutputData->safety_flags & KNIGHTSAFETY_DROPOFFFRONTRIGHT_UNSAFE;
//    flags["DROPOFF_SIDELEFT_UNSAFE"]   = lowLevelOutputData->safety_flags & KNIGHTSAFETY_DROPOFFSIDELEFT_UNSAFE;
//    flags["DROPOFF_SIDERIGHT_UNSAFE"]  = lowLevelOutputData->safety_flags & KNIGHTSAFETY_DROPOFFSIDERIGHT_UNSAFE;
//
//    for(auto &flagEntry : flags)
//    {
//        if(flagEntry.second) { /* PRINT_WARNING( << fmt("%s:%s\n") % flagEntry.first % flagEntry.second); */ }
//        else                 { /* PRINT_TRACE(   << fmt("%s:%s\n") % flagEntry.first % flagEntry.second); */ }
//    }
//
//    return lowLevelOutputData;
//}


auto SafetyBoardSim::NewStyleSafetyStuff(
    std::shared_ptr<DropOffSensorReaderMsg> const &dropOffMsg,
    std::shared_ptr<WheelEncoderReaderMsg> const &encoderMsg,
    std::shared_ptr<PlatformWriterMsg> const &platformWriterMsg
) -> void
{
    g_dropoffsensor_data.front_left.adcsample  = dropOffMsg->DropOffFrontLeft;
    g_dropoffsensor_data.front_right.adcsample = dropOffMsg->DropOffFrontRight;
    g_dropoffsensor_data.side_left.adcsample   = dropOffMsg->DropOffSideLeft;
    g_dropoffsensor_data.side_right.adcsample  = dropOffMsg->DropOffSideRight;

    g_dropoffsensor_data.front_left.mvolts     = dropOffMsg->DropOffFrontLeft  * DROPOFFSENSORS_ADC_VREF_MV;
    g_dropoffsensor_data.front_right.mvolts    = dropOffMsg->DropOffFrontRight * DROPOFFSENSORS_ADC_VREF_MV;
    g_dropoffsensor_data.side_left.mvolts      = dropOffMsg->DropOffSideLeft   * DROPOFFSENSORS_ADC_VREF_MV;
    g_dropoffsensor_data.side_right.mvolts     = dropOffMsg->DropOffSideRight  * DROPOFFSENSORS_ADC_VREF_MV;

    g_wheelencoder_data.left  = encoderMsg->LeftTicks;
    g_wheelencoder_data.right = encoderMsg->RightTicks;

    auto eventFlags = uint32_t(
        SAFETYPROC_EVENT_FLAG
//         | HALF_SECOND_EVENT_FLAG
        | ORIENTATION_EVENT_FLAG
//         | EXT_WDT_EVENT_FLAG
        | DROPOFF_EVENT_FLAG
//         | PROXIMITY_EVENT_FLAG
    );

    if(platformWriterMsg && platformWriterMsg->Data.RequestSafetyReset)
    {
        PRINT_WARNING( << "got request to clear flags!" );
        knightsafety_clear_flags();
    }

    auto preState = g_persistent_safety_state;
    eventLoopIteration(m_Orientation.get(), m_Dropoff.get(), m_Proximity.get(), eventFlags);
    auto postState = g_persistent_safety_state;

    if( preState.unsafe != postState.unsafe )
    {
        PRINT_WARNING( << fmt("pre post conditions are not same:\n%s\n%s\n\n")
            % bitset<16>(preState.unsafe) % bitset<16>(postState.unsafe) );
        PRINT_WARNING( << "dropoff sensor sl: " << g_dropoffsensor_data.side_left.mvolts  );
        PRINT_WARNING( << "dropoff sensor fl: " << g_dropoffsensor_data.front_left.mvolts );
        PRINT_WARNING( << "dropoff sensor fr: " << g_dropoffsensor_data.front_right.mvolts);
        PRINT_WARNING( << "dropoff sensor sr: " << g_dropoffsensor_data.side_right.mvolts );
        PRINT_WARNING( << "wheelencoder left : " << g_wheelencoder_data.left);
        PRINT_WARNING( << "wheelencoder right: " << g_wheelencoder_data.right);
    }
}

auto SafetyBoardSim::BuildSafetyFlagsReaderMsg(
    std::shared_ptr<DropOffSensorReaderMsg> const &dropOffMsg,
    std::shared_ptr<WheelEncoderReaderMsg> const &encoderMsg,
    std::shared_ptr<PlatformWriterMsg> const &platformWriterMsg
) -> std::shared_ptr<SafetyFlagsReaderMsg>
{
    if(!(dropOffMsg && encoderMsg))
    {
        PRINT_WARNING( << fmt("Didn't complete set of data, can't simulate safety stuff %x, %x\n") % dropOffMsg % encoderMsg );
        return nullptr;
    }

    auto safetyFlagsMsg = make_shared<SafetyFlagsReaderMsg>();

    static bool const newStyleSafetyCode = true;
    if(newStyleSafetyCode)
    {
        NewStyleSafetyStuff(dropOffMsg, encoderMsg, platformWriterMsg);

        safetyFlagsMsg->UnsafeFlags = g_persistent_safety_state.unsafe;
    }
    else
    {
//        auto lowLevelOutputData     = OldStyleSafetyStuff(dropOffMsg, encoderMsg);
//        safetyFlagsMsg->UnsafeFlags = lowLevelOutputData->safety_flags;
    }

    safetyFlagsMsg->SyncPulseTimestamp = dropOffMsg->SyncPulseTimestamp;
    safetyFlagsMsg->Timestamp          = dropOffMsg->Timestamp;

    return safetyFlagsMsg;
}


} /*namespace knight*/
} /*namespace crl*/
```

**Comment by catskul** [comment]
fixed in https://github.com/Kitware/KWStyle/pull/38
